# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(max_length=200)),
                ('act_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Act')),
            ],
        ),
        migrations.CreateModel(
            name='EnvoyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Act')),
            ],
        ),
        migrations.CreateModel(
            name='PreChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Act')),
            ],
        ),
    ]
